type SongMetadata = {
  bpm: number | null;
  style: string | null;
  coverArtUrl?: string;
  description?: string;
};

export const songMetadata: Record<string, SongMetadata> = {
  "https://deffy.me/media/MUSIC/me/classics/Heaven(def).mp3": { "bpm": 85, "style": "Pop", "description": "An uplifting pop ballad that captures the feeling of a serene, ethereal experience. With gentle melodies and soaring vocals, this track evokes a sense of peace and blissful escape, creating a truly heavenly soundscape." },
  "https://deffy.me/media/MUSIC/me/classics/Here_Without_You(def).mp3": { "bpm": 80, "style": "Pop", "description": "A poignant and melancholic pop track that beautifully expresses the deep feeling of longing for someone far away. The heartfelt lyrics and emotive melody combine to create a powerful anthem for anyone missing a loved one." },
  "https://deffy.me/media/MUSIC/me/classics/Legends_Never_Die(def).mp3": { "bpm": 135, "style": "Pop Rock", "description": "An epic and triumphant pop rock anthem that celebrates perseverance and eternal legacy. Featuring a powerful beat, driving guitar riffs, and inspirational vocals, this song is a motivational powerhouse about overcoming challenges and leaving a mark on the world." },
  "https://deffy.neocities.org/media/MUSIC/me/classics/READY_STEADY_GO(def).mp3": { "bpm": 160, "style": "J-Pop", "description": "A high-octane J-Pop track that feels like the opening theme to a thrilling anime series. Its breakneck pace, energetic vocals, and electrifying synth lines create an unstoppable sense of motion and excitement." },
  "https://deffy.me/media/MUSIC/me/classics/RISE_(ft._The_Glitch_Mob_Mako_and_The_Word_Alive)(def).mp3": { "bpm": 130, "style": "Electronicore", "description": "The iconic competitive gaming anthem that blends cinematic orchestral elements, hard-hitting electronic drops, and powerful rock vocals. 'RISE' is a testament to the struggle and glory of competition, capturing the journey of climbing to the top against all odds." },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Aaron_Carter-I_Want_Candy(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Anberlin-The_Feel_Good_Drag(def).mp3": { "bpm": 145, "style": "Alternative Rock", "description": "A powerful and driving alternative rock track that explores the intense, addictive nature of a toxic relationship. With its pulsing rhythm, raw guitar riffs, and passionate vocals, the song captures the desperate struggle between love and self-destruction." },
  "https://deffy.me/media/MUSIC/me/classics/Auli'i_Cravalho-How_Far_I'll_Go(Moana)(def).mp3": { "bpm": 98, "style": "Pop" },
  "https://deffy.me/media/MUSIC/me/classics/Austin_Mahone-Lady_ft_Pitbull(def).mp3": { "bpm": 125, "style": "Dance-Pop" },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Avicii-Fade_Into_Darkness(def).mp3": { "bpm": 128, "style": "Progressive House" },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Avril_Lavigne-Im_with_You(def).mp3": { "bpm": 75, "style": "Pop Rock" },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Ava_Max-Sweet_but_Psycho(def).mp3": { "bpm": 133, "style": "Dance-pop" },
  "https://deffy.me/media/MUSIC/me/classics/Bebe_Rexha-I_Got_You(def).mp3": { "bpm": 100, "style": "Pop" },
  "https://deffy.me/media/MUSIC/me/classics/Billy_Currington-Do_I_Make_You_Wanna(def).mp3": { "bpm": 84, "style": "Country" },
  "https://deffy.me/media/MUSIC/me/classics/blink-182-I_Miss_You(def).mp3": { "bpm": 112, "style": "Pop Punk", "description": "An iconic emo anthem that blends gothic romance with heartfelt longing. The track's distinctive acoustic riff, cello undertones, and dual vocal delivery create a haunting and unforgettable atmosphere of melancholy and love." },
  "https://deffy.me/media/MUSIC/me/classics/Broods-Superstar(def).mp3": { "bpm": 120, "style": "Electro-Pop" },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Bruno_Mars-Uptown_Funk(def).mp3": { "bpm": 115, "style": "Funk-Pop" },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Calvin_Harris-Thinking_About_You(def).mp3": { "bpm": 128, "style": "EDM" },
  "https://deffy.me/media/MUSIC/me/classics/Cartel-Wasted(def).mp3": { "bpm": 142, "style": "Trap" },
  "https://deffy.me/media/MUSIC/me/classics/Chappell_Roan-Good_Luck,_Babe!(def).mp3": { "bpm": 123, "style": "Pop" },
  "https://deffy.me/media/MUSIC/me/classics/Chappell_Roan-Pink_Pony_Club(def).mp3": { "bpm": 125, "style": "Dance-Pop" },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Chris_Brown-Dont_Wake_Me_Up(def).mp3": { "bpm": 128, "style": "Pop/R&B" },
  "https://deffy.me/media/MUSIC/me/classics/Chris_Brown-Forever(def).mp3": { "bpm": 120, "style": "R&B" },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Coldplay-A_Sky_Full_Of_Stars(def).mp3": { "bpm": 125, "style": "Dance-Pop" },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Coldplay-Clocks(def).mp3": { "bpm": 130, "style": "Alternative Rock" },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Coldplay-Princess_of_China(def).mp3": { "bpm": 120, "style": "Electropop" },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Creed-One_Last_Breath(def).mp3": { "bpm": 118, "style": "Post-Grunge" },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Daniel_Powter-Bad_Day(def).mp3": { "bpm": 137, "style": "Pop" },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Daughtry-Home(def).mp3": { "bpm": 138, "style": "Alternative Rock" },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Daughtry-Its_Not_Over(def).mp3": { "bpm": 139, "style": "Post-Grunge" },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Daughtry-Over_You(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Daughtry-September(def).mp3": { "bpm": 135, "style": "Rock" },
  "https://deffy.neocities.org/media/MUSIC/me/classics/David_Cook-Come_Back_to_Me(def).mp3": { "bpm": 115, "style": "Pop Rock" },
  "https://deffy.neocities.org/media/MUSIC/me/classics/David_Guetta-Without_You(def).mp3": { "bpm": 128, "style": "Electronic Dance Music" },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Davis_Mallory-Box_It_Up": { "bpm": 125, "style": "Pop" },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Dead_Or_Alive-You_Spin_Me_Round(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/deadmau5-Monophobia(def).mp3": { "bpm": 128, "style": "Progressive House" },
  "https://deffy.neocities.org/media/MUSIC/me/classics/deadmau5&Kaskade-I_Remember(def).mp3": { "bpm": 128, "style": "Progressive House" },
  "https://deffy.me/media/MUSIC/me/classics/Disturbed-Down_With_The_Sickness(def).mp3": { "bpm": 180, "style": "Nu Metal" },
  "https://deffy.me/media/MUSIC/me/classics/Dom_Dolla-Take_It!(def).mp3": { "bpm": 127, "style": "House" },
  "https://deffy.me/media/MUSIC/me/classics/Dwayne_Johnson-You're_Welcome(def).mp3": { "bpm": 125, "style": "Pop/Showtune" },
  "https://deffy.me/media/MUSIC/me/classics/Ed_Sheeran-Shivers(def).mp3": { "bpm": 140, "style": "Pop" },
  "https://deffy.me/media/MUSIC/me/classics/Ed_Sheeran-Thinking_Out_Loud(def).mp3": { "bpm": 79, "style": "Pop" },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Eric_Prydz-Call_on_me(def).mp3": { "bpm": 128, "style": "House" },
  "https://deffy.me/media/MUSIC/me/classics/Europe-The_Final_Countdown(def).mp3": { "bpm": 128, "style": "Hard Rock" },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Fall_Out_Boy-Sugar_We're_Goin_Down(def).mp3": { "bpm": 165, "style": "Pop Punk", "description": "The explosive pop-punk hit that defined a generation with its rapid-fire, clever lyrics and unforgettable chorus. A whirlwind of energetic guitars and soaring vocals, this song is a pure adrenaline rush of teenage angst and complicated romance." },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Fall_Out_Boy-This_Aint_A_Scene_Its_An_Arms_Race(def).mp3": { "bpm": 155, "style": "Pop Punk" },
  "https://deffy.me/media/MUSIC/me/classics/Filter-Take_A_Picture(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Fitz&The_Tantrums-The_Walker(def).mp3": { "bpm": 127, "style": "Neo-soul" },
  "https://deffy.me/media/MUSIC/me/classics/for_KING_&_Country-Love_Me_Like_I_Am(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Gavin_DeGraw-I_Dont_Want_To_be(def).mp3": { "bpm": 116, "style": "Pop Rock" },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Gavin_DeGraw-Not_Over_You(def).mp3": { "bpm": 124, "style": "Pop Rock" },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Good_Charlotte-Lifestyles_of_the_Rich&Famous(def).mp3": { "bpm": 165, "style": "Pop-Punk" },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Good_Charlotte-The_Anthem(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Gryffin,_Illenium-Feel_Good(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Haddaway-What_is_Love(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Hailee_Steinfeld-Back_to_Life(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Halsey-Now_Or_Never(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Hanson-A_Minute_Without_You(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Hanson-MMMBop(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Hilary_Duff-Come_Clean(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Hinder-Lips_of_an_Angel(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Hoobastank-Same_Direction(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Hoobastank-The_Reason(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Hooty&The_Blowfish-Only_Wanna_Be_with_You(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Imagine_Dragons-Thunder(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/James_Taylor-Secret_oLife(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Jason_Derulo-Ridin_Solo.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Jay_Sean-Do_You_Remember(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Jay_Sean-Down(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Jelly_Roll-Dancing_With_The_Devil(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Jelly_Roll-NEED_A_FAVOR(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Jelly_Roll-Save_Me(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/JOURDIN_PAULINE-SUGAR(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Jordin_Sparks-One_Step_At_A_Time(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Jordan_Sparks-Beauty_and_the_Beast(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Justin_Bieber-Ghost(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/K-Si_Yang-Want_You(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Kanye_West-Street_Lights(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Katy_Perry-Daisies(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Katy_Perry-Teenage_Dream(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Keana-Is_It_Any_Wonder(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Kelly_Clarkson-Since_U_Been_Gone(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Korn-Yall_Want_a_Single(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Kris_Kross-Jump(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Kuba_Oms-My_Love(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Lady_Antebellum-Need_You_Now(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Lana_Del_Rey-Summertime_Sadness(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/LANY-never_mind_let's_break_up(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Lauv-All_4_Nothing(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Lewis_Capaldi-Forget_Me(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Lewis_Capaldi-Someone_You_Loved(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Lukas_Graham-7_Years(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Maroon5-Maps(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Marshmello_ft._Bastille-Happier(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Mark_Ronson-Uptown_Funk(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Metro_Station-Shake_It(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Michael_Bublé-Everything(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Michael_Bublé-It's_Beginning_To_Look_A_Lot_Like_Christmas(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Miley_Cyrus-Full_Circle(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/mike_posner-looks_like_sex(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Modest_Mouse-Float_On(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Mulan-I'll_Make_A_Man_Out_of_You(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Muse-Madness(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Natalie_Imbruglia-Torn(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Nicebeatzprod-Take_Me_Slowly(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Nickelback-Someday(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/One_Direction-Night_Changes(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/One_Direction-What_Makes_You_Beautiful(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Outasight-Tonight_is_The_Night(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Paramore-crushcrushcrush(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Parachute-Kiss_Me_Slowly(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Pendulum-Streamline(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Pendulum-Witchcraft(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Phil_Collins-Another_Day_In_Paradise(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Phil_Collins-Do_You_Remember(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Phil_Collins-In_The_Air_Tonight(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Phil_Collins-Strangers_Like_Me(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Phil_Collins-Youll_Be_In_My_Heart(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Post_Malone-I_Had_Some_Help(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/PVRIS-You_and_I(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Rob_Thomas-Little_Wonders(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Sabrina_Carpenter-Espresso(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Sabrina_Carpenter-Taste(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Said_The_Sky-Over_Getting_Over_You(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Sam_Smith-Dancing_with_a_Stranger(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Sam_Smith-Im_Not_The_Only_One(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Sam_Smith-Too_Good_At_Goodbyes(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Sara_Bareilles-Brave(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Sara_Bareilles-Love_Song(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Selena_Gomez-Good_For_You(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Seven_Lions-Strangers(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Shaboozey-A_Bar_Song(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Silverchair-Straight_Lines(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Sixpence_None_The_Richer-Kiss_Me(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/SoMo-Ride(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Starley-Call_On_Me(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Survivor-Eye_Of_The_Tiger(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Taylor_Swift-Antihero(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Taylor_Swift-Blank_Space(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Taylor_Swift-Love_Story(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Taylor_Swift-You_Belong_With_Me(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Tegan_And_Sara-Back_In_Your_Head(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/The_Black_Eyed_Peas-I_Gotta_Feeling(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/The_Calling-Wherever_You_Will_Go(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/The_Chainsmokers-Paris(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/The_Killers-Mr._Brightside(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/The_Naked_And_Famous-Everybody_Knows(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/The_Starting_Line-Island(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Third_Eye_Blind-Crystal_Baller(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Thomas_Rhett-Marry_Me(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Tinie_Tempah_ft._Eric_Turner-Written(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Tory_Lanez-Say_It(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Tove_Lo-Talking_Body(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/U2-It's_a_Beautiful_Day(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Usher-Yeah(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Vicetone-Nothing_Stopping_me(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Welcome_to_the_Creature(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Welcome_to_the_Internet-Bo_Burnham(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Years&Years-King(def).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/classics/Zedd-Papercut(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Zedd-Stay_The_Night(def).mp3": { "bpm": null, "style": null },
  "https://deffy.me/media/MUSIC/me/classics/Zedd_Maren_Morris_Grey-The_Middle(def).mp3": { "bpm": null, "style": null }
};