type SongMetadata = {
  bpm: number | null;
  style: string | null;
  coverArtUrl?: string;
  description?: string;
};

export const songMetadata: Record<string, SongMetadata> = {
  "https://deffy.neocities.org/media/MUSIC/general/Ashes_Still_Sing.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Balcony_Drift.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Broken_Sky.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Busted.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Dead_Puff_Drill(Outta_Juice).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Disappear.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/GG_next.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Glass_River.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Hold_On.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Lost_in_a_Trance.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Love_Square.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Meet_Me_in_general.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/MeloJungle.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Melotruous.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Mod_Me.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Motiwait.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Neon_Funeral(Heart.exe).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Neon_Palms(City-Bossa).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/OKAY_OKAY(Do_It_Again).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Out_of_Error(CTRL+ALT+Alive).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Paper_Halo.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Rust_&_Neon(Freeway_Hymn).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Set_It_to_Sky.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Shattered_Heart.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Sidewalk_Aurora.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Signal_Collapse.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Soft_Launch(Of_a_Better_Day).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/SPIRIT.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Starlight_Machines.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Start_Here_Tonight.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/The_Best_You_Got.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/The_Unfinished_Key.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/What’s_Mine_is_Yours.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Wings_in_the_Windmill.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album1/Banned_but_not_Bent.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album1/Better_Off.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album1/Biatch_Energy.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album1/Hold_This_Moment.mp3": { "bpm": null, "style": null, "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Hold_This_Moment.jpg" },
  "https://deffy.neocities.org/media/MUSIC/jext/album1/Hylyf_(High_Life).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album1/I_Am_The_One.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album1/I_Mean_Anything.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album1/Just_Rise!.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album1/Might_As_Well.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album1/Please_Do.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album1/Point_Blank.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album1/Really_Him.mp3": { "bpm": null, "style": null, "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Really_Him.jpg" },
  "https://deffy.neocities.org/media/MUSIC/jext/album1/Sheesh.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album2/Afterimage.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album2/Almost_Said_It.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album2/Backburner_Heart.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album2/Come_Back_to_Me.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album2/Deaf_Ears.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album2/Her_Cheat_Codes.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album2/If_Only.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album2/In-between_the_Lies.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album2/Just_Dont.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album2/Just_Pretend.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album2/Left_on_Read.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album2/The_Last_Ping.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album2/Youre_Still_Here.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album3/2013.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album3/Astril_Overlord.mp3": { "bpm": null, "style": null, "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Astril_Overlord.jpg" },
  "https://deffy.neocities.org/media/MUSIC/jext/album3/Code_of_Yours.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album3/Hot_Disparity.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album3/Life_on_Mute.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album3/Offline_Boyfriend.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album3/Para-you.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album3/Spent.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album3/Walltalka.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album3/You_Me_and_the_Machines.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album3/im_a_bot.mp3": { "bpm": null, "style": null, "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/im_a_bot.jpg" },
  "https://deffy.neocities.org/media/MUSIC/jext/album3/wyw.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album4/Crashing_Out.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album4/I_Can_Change.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album4/Nerf_Me_Later.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album4/Never_Let_Go.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album4/Never_Wrong.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album4/Not_Meaningless.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album4/Out_of_Nowhere.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album4/Silent_Escape.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album4/Someone_Cares.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album4/Somewhere_Somehow.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album4/Whenever_and_Wherever.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album4/inb4.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/jext/album4/sitdown.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/lxj/LxJ-City_of_Two.mp3": { "bpm": null, "style": null, "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/City_of_Two.jpg" },
  "https://deffy.neocities.org/media/MUSIC/lxj/LxJ-Didn’t_Say_Goodbye.mp3": { "bpm": null, "style": null, "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Didnt_Say_Goodbye.jpg" },
  "https://deffy.neocities.org/media/MUSIC/lxj/LxJ-Memorys_Not_Enough.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/lxj/LxJ-Rebooted_Hearts.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/luna/Again.mp3": { "bpm": null, "style": null, "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Again.jpg" },
  "https://deffy.neocities.org/media/MUSIC/luna/All_Points_Bulletin.mp3": { "bpm": null, "style": null, "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/All_Points_Bulletin.jpg" },
  "https://deffy.neocities.org/media/MUSIC/luna/Ascend_Beyond_Time.mp3": { "bpm": null, "style": null, "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Ascend_Beyond_Time.jpg" },
  "https://deffy.neocities.org/media/MUSIC/luna/Better_Off.mp3": { "bpm": null, "style": null, "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Better_Off.jpg" },
  "https://deffy.neocities.org/media/MUSIC/luna/Carbon_Halo.mp3": { "bpm": null, "style": null, "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Carbon_Halo.jpg" },
  "https://deffy.neocities.org/media/MUSIC/luna/Closer_to_Tomorrow.mp3": { "bpm": null, "style": null, "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Closer_to_Tomorrow.jpg" },
  "https://deffy.neocities.org/media/MUSIC/luna/Echo_in_the_Dark.mp3": { "bpm": null, "style": null, "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Echo_in_the_Dark.jpg" },
  "https://deffy.neocities.org/media/MUSIC/luna/Every_Time_You_Come_Around.mp3": { "bpm": null, "style": null, "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Every_Time_You_Come_Around.jpg" },
  "https://deffy.neocities.org/media/MUSIC/luna/Hot_Paste.mp3": { "bpm": null, "style": null, "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Hot_Paste.jpg" },
  "https://deffy.neocities.org/media/MUSIC/luna/Just_Another.mp3": { "bpm": null, "style": null, "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Just_Another.jpg" },
  "https://deffy.neocities.org/media/MUSIC/luna/Middle_of_the_Night.mp3": { "bpm": null, "style": null, "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Middle_of_the_Night.jpg" },
  "https://deffy.neocities.org/media/MUSIC/luna/Never_Alone.mp3": { "bpm": null, "style": null, "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Never_Alone.jpg" },
  "https://deffy.neocities.org/media/MUSIC/luna/No_One_Knows_Me_Here.mp3": { "bpm": null, "style": null, "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/No_One_Knows_Me_Here.jpg" },
  "https://deffy.neocities.org/media/MUSIC/luna/Off-Camera.mp3": { "bpm": null, "style": null, "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Off-Camera.jpg" },
  "https://deffy.neocities.org/media/MUSIC/luna/So_What.mp3": { "bpm": null, "style": null, "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/So_What.jpg" },
  "https://deffy.neocities.org/media/MUSIC/luna/They_Said.mp3": { "bpm": null, "style": null, "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/They_Said.jpg" },
  "https://deffy.neocities.org/media/MUSIC/luna/Wildflower_Gasoline.mp3": { "bpm": null, "style": null, "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Wildflower_Gasoline.jpg" },
  "https://deffy.me/media/MUSIC/suno/Discord_Jungle_Blues.mp3": { "bpm": 172, "style": "Jungle Blues" },
  "https://deffy.neocities.org/media/MUSIC/me/suno/In_the_eyes_of_Hyde.mp3": { "bpm": 140, "style": "Heavy Metal", "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/In_the_Eyes_of_Hyde.jpg", "description": "This track is a powerful Heavy Metal anthem that delves into the duality of human nature, inspired by the classic tale of Dr. Jekyll and Mr. Hyde. The song features aggressive, down-tuned guitar riffs, thunderous double-bass drumming, and a soaring vocal performance that shifts between melodic verses and guttural, intense choruses. The lyrics explore themes of inner conflict, hidden darkness, and the struggle to control one's own monstrous impulses. The bridge introduces a brief, eerie melodic section before launching into a blistering guitar solo, showcasing technical prowess and raw emotion. It's a journey into the shadows of the psyche, perfect for fans of classic and modern metal." },
  "https://deffy.neocities.org/media/MUSIC/me/suno/IM_COMING(Late_Bloom).mp3": { "bpm": 110, "style": "Pop", "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/IM_COMING_(Late_Bloom).jpg" },
  "https://deffy.neocities.org/media/MUSIC/me/suno/Ill_Show_Me.mp3": { "bpm": 110, "style": "Pop", "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Ill_Show_Me.jpg" },
  "https://deffy.neocities.org/media/MUSIC/me/suno/Hyde_Kitty.mp3": { "bpm": 125, "style": "Indie Pop", "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Hyde_Kitty.jpg" },
  "https://deffy.neocities.org/media/MUSIC/me/suno/Fyxion_Awakening.mp3": { "bpm": 138, "style": "Trance", "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Fyxion_Awakening.jpg" },
  "https://deffy.neocities.org/media/MUSIC/me/suno/DEFCON_ROAST.mp3": { "bpm": 98, "style": "Hip-Hop", "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/DEFCON_ROAST.jpg" },
  "https://deffy.neocities.org/media/MUSIC/me/suno/Creature_Alive(Pyah).mp3": { "bpm": 130, "style": "Electro House", "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Creature_Alive_(Pyah).jpg" },
  "https://deffy.neocities.org/media/MUSIC/me/suno/Born_with_the_Internet.mp3": { "bpm": 120, "style": "Electronic Pop", "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Born_with_the_Internet.jpg" },
  "https://deffy.neocities.org/media/MUSIC/me/suno/Become.mp3": { "bpm": 105, "style": "Electronic" },
  "https://deffy.neocities.org/media/MUSIC/me/suno/Vaelix_the_GOAT.mp3": { "bpm": 135, "style": "Electronic", "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Vaelix_the_GOAT.jpg" },
  "https://deffy.neocities.org/media/MUSIC/me/suno/Vaelix(Creature_of_the_Signal).mp3": { "bpm": 130, "style": "Electronic", "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Vaelix(Creature_of_the_Signal).jpg" },
  "https://deffy.neocities.org/media/MUSIC/me/suno/The_17th_Hour(Remix).mp3": { "bpm": 125, "style": "Electronic", "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/The_17th_Hour.jpg" },
  "https://deffy.neocities.org/media/MUSIC/me/suno/PYAHNIFICENT.mp3": { "bpm": 150, "style": "Hip-Hop" },
  "https://deffy.neocities.org/media/MUSIC/me/suno/To_Be_Continued(Gigi).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/suno/the_creature.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/suno/Pink_Gorilla_Club.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/suno/Mr_Hyde.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/suno/Evah_DPM.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/suno/Creature_Feature(diss_rap).mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/suno/acu/Dr_Fyxius_rap.mp3": { "bpm": 98, "style": "Rap", "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Dr_Fyxius_Rap.jpg", "description": "Opening like a measured consult—“evidence first, opinions last”—the song documents Jeff Fixius choosing clarity over comfort, then codifying that choice into an identity: “Jeff was the study… I became one.” The hook rejects miracle-speak for methodology, and the name shift into “Dr. Fyxius” marks a rite where stories are repaired, not buried. The rap section converts lab calm into field triage: lab coat → lab code, scalpel-sharp syllables, patch notes that install a “new spine,” with Kiox’s clue and Ymzo’s ticking discipline folded into protocol. Throughout, the Spire’s voltage is grounded “to grace,” which is the ACU’s heart for Fyxius—turning panic into procedure, stitching hope with aseptic poetics. It’s an origin anthem for the Continuum’s repairman-philosopher: diagnosis as duty, discharge as dignity, and method as the only magic that lasts." },
  "https://deffy.neocities.org/media/MUSIC/me/suno/acu/Chaos_Incarnate-Kiox.mp3": { "bpm": 180, "style": "Industrial Metal", "description": "These lyrics paint Kiox not as a chaos-monger but as a patient scientist of the wild: coffee spirals become galaxies, traffic lights pulse like a metronome, dice whisper toward a mean. Verse by verse he reframes “random” as readable—double pendulums sketching air, Lorenz in the hallway, butterflies tuning reality one breath at a time—while the refrain insists that chaos worn “like calm” is simply math held gently. The Spire’s voltage hum gets “lowered in the gain,” turning noise into a teachable signal; the bridge’s strange-attractor assurance (“you’re safer than you think, right here”) anchors the ACU theme that guidance doesn’t smother freedom, it reveals pattern within it. In the Continuum, this is Kiox’s pedagogy: probability over prophecy, kindness as a constant, and courage as the act of observing until the waves confess their order." },
  "https://deffy.neocities.org/media/MUSIC/me/suno/acu/Akamuy-Connection_Lost.mp3": { "bpm": 128, "style": "Electronic", "description": "An NPC’s quiet awakening scored in UI blips and soft static, the lyrics track Akamuy’s looped lines at the cedar gate—pointing west, waving on a timer—until small ruptures let feeling through. Carson’s tea, a learned laugh that “almost sits,” and the image of a “pine-green choir” hint at personhood budding inside the dialogue tree. When the signal drops—error pings, radio stutter, the cold “Resume dialogue tree B”—the song frames what the ACU often hides: under every helpful prompt is a someone trying to stay. The closing request for a “small blue flower by the gate” turns players into co-conspirators, smuggling meaning into the loop. In ACU lore, that’s how worlds change: not with grand exploits, but with a saved line in the sunlight and an NPC who refuses to be only a waypoint." },
  "https://deffy.neocities.org/media/MUSIC/me/suno/acu/Abigails_Fate.mp3": { "bpm": 95, "style": "Film Score", "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Abigails_Fate.jpg", "description": "A metamorphosis ballad where the singer refuses a destiny handed down by Spire pages and ticking clocks. The verses catalog pressure from every direction—Kiox whispering rumor, Ymzo’s metronome of obedience, riddled measurements of worth—until the pre-chorus folds a “paper moon” and pockets it as a private key. Across the hook she renames herself Sinira without erasing Abigail, turning the old name into a “memory key” and using it to pick the lock of prophecy. Lines like “I redraw the constellations” and “I’m the lantern in the hallway where the old gods misconnect” weld personal revolt to ACU cosmology: stars, scripts, and gods are just architectures to be re-authored. The bridge’s margin-signed fire makes it canon—this isn’t a costume change; it’s a rewrite of the room she was told to live in. In the Continuum, “Abigail’s fate” becomes a spell you cast on fate itself." },
  "https://deffy.neocities.org/media/MUSIC/me/suno/acu/Astrilan_Theme.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/suno/acu/VyCorp-SuperFyX_Vector.mp3": { "bpm": 160, "style": "Electronic", "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/VyCorp-SuperFyX_Vector.jpg" },
  "https://deffy.neocities.org/media/MUSIC/me/suno/acu/VyCorp-Risk_Committee.mp3": { "bpm": 120, "style": "Industrial" },
  "https://deffy.neocities.org/media/MUSIC/me/suno/acu/The_Spire.mp3": { "bpm": 90, "style": "Ambient", "description": "A civic hymn and onboarding ritual, “The Spire” invites you to where neon learns to sing and tick becomes oath. Ymzo narrates with brass-toothed imagery—elevator thunder, cable chorales, copper rails—while Kiox maps voltage and Sinira paints dawn, Thajal already a rumor on the rooftops. The lyric keeps correcting the normie misread (“not a cloud, but a design”): it’s not a stairwell into haze; it’s an instrument you play, turning doubt to gold one tread at a time. Bring a relic, hold it to the light—angles align, edges write—and when the vault hisses OPEN and clocks converge as one, you sign the seal and step inside. In ACU canon, the Spire isn’t a high; it’s courage meeting time, a machine that translates intention into passage." },
  "https://deffy.neocities.org/media/MUSIC/me/suno/acu/Skydrift_over_Erythaeum.mp3": { "bpm": 75, "style": "Ambient" },
  "https://deffy.neocities.org/media/MUSIC/me/suno/acu/Snackin_on_the_Forbidden.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/suno/acu/Still_Not_Dreaming-Shiz.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/suno/acu/Next_Time-Sinira.mp3": { "bpm": 125, "style": "Alternative Rock", "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Next_Time-Sinira.jpg", "description": "A precise boundary-setting answer song, “Next Time” meets a data-drunk suitor with an ocean’s refusal. Sinira won’t be graphed, renamed, or curved to fit someone else’s chalkboard; she signs the margin with her own sky and asks to be met in motion, not modeled. The choruses lay out terms of engagement—bring a door, not a drawing; arrive as an equal or be left as a stepping stone—while verse two nods directly to Kiox, respecting his cleverness without surrendering the flame. In the ACU’s lexicon, this is anti-extraction love: if you can lift as she lifts, realign; otherwise, let the road be a road. The Spire hums, she changes the key, and the lesson stands—do not mistake access to a pattern for access to a person." },
  "https://deffy.neocities.org/media/MUSIC/me/suno/acu/Love_in_Disguise-Vircy.mp3": { "bpm": 120, "style": "Pop", "description": "A glittering predator of a song, sung from the perspective of a groomer who tilts a prism until “Tyler” sees only candy colors while The Corrupted wait just offstage. Every line weaponizes tenderness: promises tuned to his favorite song, “sugar on the edges,” a safety story told while she walks him to the gate “where quieter teeth cling.” The chorus names the trick—sunshine on sharpened wire—while the bridge absolves the abuser (“don’t blame the prism”) and admits the package is a ribbon on a poisoned gift. In ACU terms, this is how corruption often travels: not as a roar but as “mercy” that anesthetizes discernment, falsifying the Spire’s report (“he’s fine”) and color-shifting danger into rose. It’s a cautionary tableau—how aesthetics become bait, and how love, misnamed, can smuggle an entire choir of harm behind one bright eye." },
  "https://deffy.neocities.org/media/MUSIC/me/suno/acu/Khaos_Krystal.mp3": { "bpm": 150, "style": "Industrial Metal", "description": "A gentle praxis hymn, “Khaos Krystal” treats a faceted stone as a thinking aid, not a miracle—“frozen lightning” that turns noise toward meaning when you tilt it just so. The lyric keeps returning to patient method: count to three, lower the gain, let chance become geometry. Cameos from Vircy (patience), Ymzo (measured time), and Sinira (redrawing the moon) situate the piece within the ACU’s triad of poise, order, and rebellion, while Kiox’s voice refuses certainty in favor of “a truer frame for trembling hands.” Even the lore nod—Greek Khaos as space-to-start-again—keeps the focus on interpretation over prophecy. It’s the Continuum’s ethic in miniature: align a facet, find the pattern, let mercy calibrate the plan." },
  "https://deffy.neocities.org/media/MUSIC/me/suno/acu/Kiox_vs_Ymzo.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/suno/acu/ITZvsPAUS-rap_battle.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/me/suno/acu/Ill_Sin_For_You.mp3": { "bpm": 120, "style": "Gothic Rock", "coverArtUrl": "https://deffy.neocities.org/media/MUSIC/coverart/Ill_Sin_For_You.jpg", "description": "A confession dressed in math, this song traces a scientist’s heart tilting toward Sinira until prediction gives way to participation. The verses stack Kiox-flavored imagery—Lorenz halls, strange attractors, sine curves—around the catalyst of her renaming (“you said ‘Abigail,’ then changed the move”), showing how Sinira’s fate-bending turns his proofs to blush. Each chorus vows a voluntary asymmetry—“break symmetry, bend through”—as the narrator reframes law as something that can “learn you,” not cage you. Quantum shades flicker in the bridge’s “collapse my wave,” while the final refrain swaps theory for choice: “I choose you.” In the ACU, that’s the pivot from modeling the Continuum to loving inside it—chaos as devotion, science as tenderness, and Sinira as the attractor that makes courage measurable." },
  "https://deffy.neocities.org/media/MUSIC/me/suno/acu/High_Realm.mp3": { "bpm": 125, "style": "Progressive Electronic", "description": "A clockwork procession and a naming correction—“HYRUM”—declare the song’s thesis: this realm isn’t a narcotic high but the craft of measure. Keys, vaults, and fivefold locks set a ritual of entry where time “stands up” when written down, stairs are set rather than climbed, and wind gets numbered until courage squares its shoulders. The chorus functions like an oath—helm, seal, ledge—inviting the listener to align gears and step to the sovereign drum; verses nod to Kiox mapping thunder and Sinira’s flame while the narrator keeps the ledger where hours claim what’s real. When the vault hisses OPEN, the piece becomes a civic hymn for the ACU’s ordered height: speak the true name, sign the seal, and watch the city learn the tick as hymn—because in HYRUM, measure isn’t control; it’s the doorway that returns what was lost." },
  "https://deffy.neocities.org/media/MUSIC/general/Borrowed_Constellations.mp3": { "bpm": 95, "style": "Dream Pop" },
  "https://deffy.neocities.org/media/MUSIC/general/Blue_Hour_Signal.mp3": { "bpm": 85, "style": "Ambient Electronic" },
  "https://deffy.neocities.org/media/MUSIC/general/Arrivals(Porch_Light_On).mp3": { "bpm": 98, "style": "Indie Folk" },
  "https://deffy.neocities.org/media/MUSIC/general/Arcane_Intellect.mp3": { "bpm": 80, "style": "Cinematic Orchestral" },
  "https://deffy.neocities.org/media/MUSIC/general/Arcane_Dream.mp3": { "bpm": 85, "style": "Ambient Electronic" },
  "https://deffy.neocities.org/media/MUSIC/general/WAKE_UP_CHAT.mp3": { "bpm": 135, "style": "Electro-Pop" },
  "https://deffy.neocities.org/media/MUSIC/general/Unboxed(Remix).mp3": { "bpm": 125, "style": "Electronic" },
  "https://deffy.neocities.org/media/MUSIC/general/Tomorrows_Today.mp3": { "bpm": 115, "style": "Contemporary Pop" },
  "https://deffy.neocities.org/media/MUSIC/general/Tomorrows_Today(Remix).mp3": { "bpm": 125, "style": "Electronic Dance Music" },
  "https://deffy.neocities.org/media/MUSIC/general/Snowy_Memory.mp3": { "bpm": 70, "style": "Ambient Instrumental" },
  "https://deffy.neocities.org/media/MUSIC/general/Silent_Water.mp3": { "bpm": 72, "style": "Ambient" },
  "https://deffy.neocities.org/media/MUSIC/general/Sacred_Filth.mp3": { "bpm": 160, "style": "Blackened Death Metal" },
  "https://deffy.neocities.org/media/MUSIC/general/Rise_to_Singularity.mp3": { "bpm": 132, "style": "Progressive Electronic" },
  "https://deffy.neocities.org/media/MUSIC/general/Rewind_with_a_Pencil.mp3": { "bpm": 95, "style": "Indie Pop" },
  "https://deffy.neocities.org/media/MUSIC/general/Read_Between_the_lines.mp3": { "bpm": 113, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Paper_Skies.mp3": { "bpm": 97, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Normified.mp3": { "bpm": 142, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Normie.mp3": { "bpm": 148, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Mind_Arcade.mp3": { "bpm": 124, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Miles_to_Maybe.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Miles_Artifact.mp3": { "bpm": 138, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Lights_in_the_Chaos.mp3": { "bpm": 125, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Lifes_Peak.mp3": { "bpm": 128, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Keep_the_Signal.mp3": { "bpm": 128, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Joystick.mp3": { "bpm": 99, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/In_the_Shadow_of_the_Grove.mp3": { "bpm": 115, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Hyperlight_Heart.mp3": { "bpm": 130, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Going_Nowhere.mp3": { "bpm": 120, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Glass_Veins.mp3": { "bpm": 92, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Frozen_Liquid.mp3": { "bpm": 174, "style": "dance" },
  "https://deffy.neocities.org/media/MUSIC/general/Flood_the_Floor.mp3": { "bpm": 108, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Erythaeum_Sunpaths.mp3": { "bpm": null, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Erythaeum_Sunpaths(2).mp3": { "bpm": 103, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Electric_Air.mp3": { "bpm": 100, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Echoes_in_Color.mp3": { "bpm": 98, "style": null },
  "https://deffy.neocities.org/media/MUSIC/general/Double_Exposure.mp3": { "bpm": 124, "style": "electronic dance" },
  "https://deffy.neocities.org/media/MUSIC/general/Death_and_Taxes.mp3": { "bpm": 124, "style": "pop" },
  "https://deffy.neocities.org/media/MUSIC/general/Crowd_Goes_Pyah.mp3": { "bpm": 113, "style": "pop" },
  "https://deffy.neocities.org/media/MUSIC/general/Crashing_In.mp3": { "bpm": 124, "style": "electronic dance" }
};